"""Initial migration

Revision ID: 5571da06f2ca
Revises: 
Create Date: 2023-12-29 21:23:14.087737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5571da06f2ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('white_player_id', sa.Integer(), nullable=True),
    sa.Column('black_player_id', sa.Integer(), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.Column('moves', postgresql.ARRAY(sa.String(length=7)), nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['white_player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###
